#!/usr/bin/env python3

output_file = "fonts/lv_symbol_def.h"

symbols_array = [
[0xe568,'HEAT_BED'],
[0xf2c9,'EXTRUDER'],
[0xf0ca,'LIST'],
[0xf715,'SLASH'],
[0xf012,'STATION_MODE'],
[0xf519,'ACCESS_POINT'],
[0xf00c,'OK'],
[0xe596,'PROBE_CHECK'],
[0xf00d,'CLOSE'],
[0xf011,'POWER'],
[0xf028,'VOLUME_HIGH'],
[0xf027,'VOLUME_LOW'],
[0xf6a9,'VOLUME_OFF'],
[0xf013,'SETTINGS'],
[0xf2d1,'NO_HEAT_BED'],
[0xe040,'HEAT_EXTRUDER'],
[0xf2ed,'TRASH'],
[0xe3af,'HOME'],
[0xf019,'DOWNLOAD'],
[0xf021,'REFRESH'],
[0xf304,'EDIT'],
[0xf048,'PREVIOUS'],
[0xf051,'NEXT'],
[0xf04b,'PLAY'],
[0xf04c,'PAUSE'],
[0xf0c7,'SAVE'],
[0xf0e0,'MESSAGE'],
[0xf0e7,'LASER'],
[0xf76f,'VACCUM'],
[0xf1f6,'DISABLE_ALERT'],
[0xf023,'LOCK'],
[0xf2dc,'COOLANT'],
[0xf04d,'STOP'],
[0xf1eb,'WIFI'],
[0xf071,'WARNING'],
[0xf07b,'FOLDER'],
[0xf15b,'FILE'],
[0xf11c,'KEYBOARD'],
[0xf55a,'BACKSPACE'],
[0xf7c2,'SD_CARD'],
[0xf0b2,'JOG'],
[0xf077,'UP'],
[0xf078,'DOWN'],
[0xf053,'LEFT'],
[0xf054,'RIGHT'],
[0xf120,'COMMAND'],
[0xf624,'GAUGE'],
[0xf1ab,'LANGUAGE'],
[0xf863,'FAN'],
[0xf48b,'SPEED'],
[0xf72b,'WIZARD'],
[0xf185,'LIGHT'],
[0xf5c1,'ENGINE'],
[0xf5fd,'LAYERS'],
[0xe4b8,'LEVELING'],
[0xf4db,'FILAMENT'],
[0xe4bd,'CENTER'],
[0xf002,'SEARCH'],
[0xf4d7,'FILAMENT_SENSOR'],
[0xf2cc,'MIST'],
[0xf13e,'UNLOCK'],
[0xf192,'LASER_2'],
[0xe4c3,'MILLING'],
[0xf3e5,'NEW_LINE'],
[0xf293,'BLUETOOTH'],
[0xf287,'USB'],
[0xf0a1,'MORE_INFO']
]
total_items = len(symbols_array)

header_file = "//This file is generated by a script do not change it\n" \
"#ifndef LV_SYMBOL_DEF_H\n" \
"#define LV_SYMBOL_DEF_H\n" \
" \n" \
"#ifdef __cplusplus\n" \
"extern \"C\" {\n" \
"#endif\n" \
" \n" \
"#include \"../lv_conf_internal.h\" \n" \
" \n" \
"/*-------------------------------\n" \
"* Symbols from \"normal\" font\n" \
"*-----------------------------*/\n" \
"#if !defined LV_SYMBOL_BULLET\n" \
"#define LV_SYMBOL_BULLET          \" \\xE2\\x80\\xA2\" /*20042, 0x2022*/\n" \
"#endif\n" \
"\n" \
"/*-------------------------------\n" \
" * Symbols from FontAwesome font\n" \
"*-----------------------------*/\n" \
"\n" \
"/*In the font converter use this list as range:\n"

header_file2 ="\n*/\n" \
"\n" \
"/* These symbols can be prefined in the lv_conf.h file.\n" \
"* If they are not predefined, they will use the following values\n\n" \
"*/\n"

enum_file_part1 = "#if !defined LV_SYMBOL_DUMMY\n" \
"/** Invalid symbol at (U+F8FF). If written before a string then `lv_img` will show it as a label*/\n" \
"#define LV_SYMBOL_DUMMY           \"\\xEF\\xA3\\xBF\"\n" \
"#endif\n" \
"\n" \
"enum {\n"

enum_file_part2="    _LV_STR_SYMBOL_DUMMY,\n};\n"

footer_file = " \n" \
"#ifdef __cplusplus\n" \
"} /*extern \"C\"*/\n" \
"#endif\n" \
" \n" \
"#endif /*LV_SYMBOL_DEF_H*/\n" \
" \n"

#Open file for writing and overwrite current
f = open(output_file, "w")
#Write header part 1
f.write(header_file)
i = 0
#Write Symbols range
for item in symbols_array:
  if i==0:
    f.write("      ")
  f.write(str(item[0]))
  total_items = total_items-1
  if total_items>0:
    f.write(",")
  i=i+1
  if i==8:
    f.write("\n")
    i=0
#Write header part 2
f.write(header_file2)
#Write Symboles definitions
for item in symbols_array:
  c = chr(item[0])
  f.write("#if !defined LV_SYMBOL_"+ item[1] + "\n")
  f.write("#define LV_SYMBOL_"+ item[1] + "           \"")
  s =str(c.encode('utf8')).upper().replace("X","x")
  s = s.replace("B'\\","\\").replace("'","")
  f.write(s)
  f.write("\""+ " /*"+str(item[0])+", "+hex(item[0]).upper().replace("X","x")+"*/"+ "\n")
  f.write("#endif\n\n")

#Write enum part
f.write(enum_file_part1)
for item in symbols_array:
  f.write("    _LV_STR_SYMBOL_"+item[1]+ ",\n")
f.write(enum_file_part2)

#Write footer
f.write(footer_file)
#Close file
f.close()

#open and read the file after the overwriting:
f = open(output_file, "r")
print(f.read())
