if(ESP32S3_8048S070C)
    set(TFT_TARGET "ESP32S3_8048S070C")
    set(SDKCONFIG ${CMAKE_SOURCE_DIR}/hardware/common/sdkconfig/ESP32-S3/with_PSRAM/16MB_Flash)    
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/ESP32S3_8048S070C/components)
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/drivers_video_rgb)
    add_compile_options("-I${CMAKE_SOURCE_DIR}/hardware/ESP32S3_8048S070C/components/bsp")
    if(HARDWARE_MOD_GT911_INT)
        add_compile_options(-DWITH_GT911_INT=1)
    endif()
endif()