if(ESP32S3_CUSTOM)
    set(TFT_TARGET "ESP32S3_CUSTOM")
    set(SDKCONFIG ${CMAKE_SOURCE_DIR}/hardware/ESP32S3_CUSTOM/sdkconfig)
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/ESP32S3_CUSTOM/components)
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/drivers_usb_otg)
    add_compile_options("-I${CMAKE_SOURCE_DIR}/hardware/ESP32S3_CUSTOM/components/bsp")    
    add_compile_options(-DESP3D_USB_SERIAL_FEATURE=1)
endif()