if (ESP32_2432S028R)
    set(TFT_TARGET "ESP32_2432S028R")
    set(SDKCONFIG ${CMAKE_SOURCE_DIR}/hardware/common/sdkconfig/ESP32/no_PSRAM/4MB_Flash)    
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/ESP32_2432S028R/components)
    add_compile_options("-I${CMAKE_SOURCE_DIR}/hardware/ESP32_2432S028R/components/bsp")
    if(HARDWARE_MOD_EXT_PSRAM)
        add_compile_options(-DWITH_PSRAM=1)
        if(HARDWARE_MOD_16MB_FLASH)
            set(SDKCONFIG ${CMAKE_SOURCE_DIR}/hardware/common/sdkconfig/ESP32/with_PSRAM/16MB_Flash)
        elseif(HARDWARE_MOD_8MB_FLASH)
            set(SDKCONFIG ${CMAKE_SOURCE_DIR}/hardware/common/sdkconfig/ESP32/with_PSRAM/8MB_Flash)
        else()
            set(SDKCONFIG ${CMAKE_SOURCE_DIR}/hardware/common/sdkconfig/ESP32/with_PSRAM/4MB_Flash)
        endif()
    endif()
endif()