if(ESP32S3_8048_TOUCH_LCD_7)
    set(TFT_TARGET "ESP32S3_8048_TOUCH_LCD_7")
    set(SDKCONFIG ${CMAKE_SOURCE_DIR}/hardware/common/sdkconfig/ESP32-S3/with_PSRAM/8MB_Flash)    
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/ESP32S3_8048_TOUCH_LCD_7/components)
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/drivers_video_rgb)
    add_compile_options("-I${CMAKE_SOURCE_DIR}/hardware/ESP32S3_8048_TOUCH_LCD_7/components/bsp")
    add_compile_options(-DWITH_GT911_INT=1)
    # Add specific usb driver for otg
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/drivers_usb_otg)
    if (USB_SERIAL_SERVICE)
        # Enable USB-OTG as serial alternative for communications
        add_compile_options(-DESP3D_USB_SERIAL_FEATURE=1)
    endif()
    set (RESOLUTION_SCREEN "res_800_480")
endif()
