if(ESP32S3_HMI43V3)
    set(TFT_TARGET "ESP32S3_HMI43V3")    
    set(SDKCONFIG  ${CMAKE_SOURCE_DIR}/hardware/ESP32S3_HMI43V3/sdkconfig)
    list(APPEND EXTRA_COMPONENT_DIRS ${CMAKE_SOURCE_DIR}/hardware/ESP32S3_HMI43V3/components)
    add_compile_options("-I${CMAKE_SOURCE_DIR}/hardware/ESP32S3_HMI43V3/components/bsp")
    add_compile_options(-DESP3D_USB_SERIAL_FEATURE=1)
endif()