//Pins definition for ESP32S3_HMI43V3
//Touch driver FT5X06 I2C
#pragma once

#include "driver/uart.h"
#include "driver/gpio.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ESP3D_SERIAL_PORT UART_NUM_0
#define ESP3D_SERIAL_BAUDRATE 115200
#define ESP3D_SERIAL_RX_PIN 44
#define ESP3D_SERIAL_TX_PIN 43
#define ESP3D_SERIAL_DATA_BITS UART_DATA_8_BITS
#define ESP3D_SERIAL_PARITY UART_PARITY_DISABLE
#define ESP3D_SERIAL_STOP_BITS UART_STOP_BITS_1
#define ESP3D_SERIAL_FLOW_CTRL UART_HW_FLOWCTRL_DISABLE
#define ESP3D_SERIAL_SOURCE_CLK UART_SCLK_APB
#define ESP3D_SERIAL_RX_BUFFER_SIZE 512
#define ESP3D_SERIAL_TX_BUFFER_SIZE 0
#define ESP3D_SERIAL_RX_TASK_SIZE 4092
#define ESP3D_SERIAL_TASK_CORE 1
#define ESP3D_SERIAL_TASK_PRIORITY 10


#ifdef __cplusplus
} /* extern "C" */
#endif