# DO NOT EDIT THIS FILE

# ===========================================
# Color Definitions
# ===========================================


  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")


# ===========================================
# Helper Functions
# ===========================================

function(check_single_selection var_list error_message selected_item)
    set(selected_count 0)
    set(last_selected "")
    foreach(item ${${var_list}})
        if(${item})
            math(EXPR selected_count "${selected_count} + 1")
            set(last_selected ${item})
        endif()
    endforeach()

    if(selected_count EQUAL 0)
        message(FATAL_ERROR "\n${BoldRed}No ${error_message} selected. Please select one in CMakeLists.txt${ColourReset}\n")
    elseif(selected_count GREATER 1)
        message(STATUS "\n\n${BoldRed}Multiple ${error_message}s selected:${ColourReset}")
        foreach(item ${${var_list}})
            if(${item})
                message(STATUS "  ${BoldRed}${item}${ColourReset}")
            endif()
        endforeach()
        message(STATUS "\n")
        message(FATAL_ERROR "\n${BoldRed}Please select only one ${error_message} in CMakeLists.txt${ColourReset}\n")
    else()
        message(STATUS "${Green}Selected ${error_message}: ${last_selected}${ColourReset}\n")
        set(${selected_item} ${last_selected} PARENT_SCOPE)
    endif()
endfunction()

# ===========================================
# Firmware Target Check
# ===========================================

set (fw_target "")
check_single_selection(FIRMWARES_LIST "firmware target" fw_target)

# ===========================================
# Target Board Check
# ===========================================

if(NOT TFT_TARGET)
    message(FATAL_ERROR 
        "\n"
        "${BoldRed}No hardware target defined. Please define a target in CMakeLists.txt${ColourReset}"
        "\n"
        "Now cmake will exit\n")
endif()


# ===========================================
# Platform Check
# ===========================================
set (board_target "")
check_single_selection(PLATFORMS_LIST "platform" board_target)

