//This file is generated by a script do not change it
#ifndef LV_SYMBOL_DEF_H
#define LV_SYMBOL_DEF_H
 
#ifdef __cplusplus
extern "C" {
#endif
 
#include "../lv_conf_internal.h" 
 
/*-------------------------------
* Symbols from "normal" font
*-----------------------------*/
#if !defined LV_SYMBOL_BULLET
#define LV_SYMBOL_BULLET          " \xE2\x80\xA2" /*20042, 0x2022*/
#endif

/*-------------------------------
 * Symbols from FontAwesome font
*-----------------------------*/

/*In the font converter use this list as range:
      58728,62153,61642,63253,61458,62745,61452,58774,
      61453,61457,61480,61479,63145,61459,62161,57408,
      62189,58287,61465,61473,62212,61512,61521,61515,
      61516,61639,61664,61671,63343,61942,61475,62172,
      61517,61931,61553,61563,61787,61724,62810,63426,
      61618,61559,61560,61523,61524,61728,63012,61867,
      63587,62603,63275,61829,62913,62973,58552,62683,
      58557,61442,62679,62156,61758,61842,58563,62437,
      62099,62087,61601,61525,61526
*/

/* These symbols can be prefined in the lv_conf.h file.
* If they are not predefined, they will use the following values

*/
#if !defined LV_SYMBOL_HEAT_BED
#define LV_SYMBOL_HEAT_BED           "\xEE\x95\xA8" /*58728, 0xE568*/
#endif

#if !defined LV_SYMBOL_EXTRUDER
#define LV_SYMBOL_EXTRUDER           "\xEF\x8B\x89" /*62153, 0xF2C9*/
#endif

#if !defined LV_SYMBOL_LIST
#define LV_SYMBOL_LIST           "\xEF\x83\x8A" /*61642, 0xF0CA*/
#endif

#if !defined LV_SYMBOL_SLASH
#define LV_SYMBOL_SLASH           "\xEF\x9C\x95" /*63253, 0xF715*/
#endif

#if !defined LV_SYMBOL_STATION_MODE
#define LV_SYMBOL_STATION_MODE           "\xEF\x80\x92" /*61458, 0xF012*/
#endif

#if !defined LV_SYMBOL_ACCESS_POINT
#define LV_SYMBOL_ACCESS_POINT           "\xEF\x94\x99" /*62745, 0xF519*/
#endif

#if !defined LV_SYMBOL_OK
#define LV_SYMBOL_OK           "\xEF\x80\x8C" /*61452, 0xF00C*/
#endif

#if !defined LV_SYMBOL_PROBE_CHECK
#define LV_SYMBOL_PROBE_CHECK           "\xEE\x96\x96" /*58774, 0xE596*/
#endif

#if !defined LV_SYMBOL_CLOSE
#define LV_SYMBOL_CLOSE           "\xEF\x80\x8D" /*61453, 0xF00D*/
#endif

#if !defined LV_SYMBOL_POWER
#define LV_SYMBOL_POWER           "\xEF\x80\x91" /*61457, 0xF011*/
#endif

#if !defined LV_SYMBOL_VOLUME_HIGH
#define LV_SYMBOL_VOLUME_HIGH           "\xEF\x80\xA8" /*61480, 0xF028*/
#endif

#if !defined LV_SYMBOL_VOLUME_LOW
#define LV_SYMBOL_VOLUME_LOW           "\xEF\x80\xA7" /*61479, 0xF027*/
#endif

#if !defined LV_SYMBOL_VOLUME_OFF
#define LV_SYMBOL_VOLUME_OFF           "\xEF\x9A\xA9" /*63145, 0xF6A9*/
#endif

#if !defined LV_SYMBOL_SETTINGS
#define LV_SYMBOL_SETTINGS           "\xEF\x80\x93" /*61459, 0xF013*/
#endif

#if !defined LV_SYMBOL_NO_HEAT_BED
#define LV_SYMBOL_NO_HEAT_BED           "\xEF\x8B\x91" /*62161, 0xF2D1*/
#endif

#if !defined LV_SYMBOL_HEAT_EXTRUDER
#define LV_SYMBOL_HEAT_EXTRUDER           "\xEE\x81\x80" /*57408, 0xE040*/
#endif

#if !defined LV_SYMBOL_TRASH
#define LV_SYMBOL_TRASH           "\xEF\x8B\xAD" /*62189, 0xF2ED*/
#endif

#if !defined LV_SYMBOL_HOME
#define LV_SYMBOL_HOME           "\xEE\x8E\xAF" /*58287, 0xE3AF*/
#endif

#if !defined LV_SYMBOL_DOWNLOAD
#define LV_SYMBOL_DOWNLOAD           "\xEF\x80\x99" /*61465, 0xF019*/
#endif

#if !defined LV_SYMBOL_REFRESH
#define LV_SYMBOL_REFRESH           "\xEF\x80\xA1" /*61473, 0xF021*/
#endif

#if !defined LV_SYMBOL_EDIT
#define LV_SYMBOL_EDIT           "\xEF\x8C\x84" /*62212, 0xF304*/
#endif

#if !defined LV_SYMBOL_PREVIOUS
#define LV_SYMBOL_PREVIOUS           "\xEF\x81\x88" /*61512, 0xF048*/
#endif

#if !defined LV_SYMBOL_NEXT
#define LV_SYMBOL_NEXT           "\xEF\x81\x91" /*61521, 0xF051*/
#endif

#if !defined LV_SYMBOL_PLAY
#define LV_SYMBOL_PLAY           "\xEF\x81\x8B" /*61515, 0xF04B*/
#endif

#if !defined LV_SYMBOL_PAUSE
#define LV_SYMBOL_PAUSE           "\xEF\x81\x8C" /*61516, 0xF04C*/
#endif

#if !defined LV_SYMBOL_SAVE
#define LV_SYMBOL_SAVE           "\xEF\x83\x87" /*61639, 0xF0C7*/
#endif

#if !defined LV_SYMBOL_MESSAGE
#define LV_SYMBOL_MESSAGE           "\xEF\x83\xA0" /*61664, 0xF0E0*/
#endif

#if !defined LV_SYMBOL_LASER
#define LV_SYMBOL_LASER           "\xEF\x83\xA7" /*61671, 0xF0E7*/
#endif

#if !defined LV_SYMBOL_VACCUM
#define LV_SYMBOL_VACCUM           "\xEF\x9D\xAF" /*63343, 0xF76F*/
#endif

#if !defined LV_SYMBOL_DISABLE_ALERT
#define LV_SYMBOL_DISABLE_ALERT           "\xEF\x87\xB6" /*61942, 0xF1F6*/
#endif

#if !defined LV_SYMBOL_LOCK
#define LV_SYMBOL_LOCK           "\xEF\x80\xA3" /*61475, 0xF023*/
#endif

#if !defined LV_SYMBOL_COOLANT
#define LV_SYMBOL_COOLANT           "\xEF\x8B\x9C" /*62172, 0xF2DC*/
#endif

#if !defined LV_SYMBOL_STOP
#define LV_SYMBOL_STOP           "\xEF\x81\x8D" /*61517, 0xF04D*/
#endif

#if !defined LV_SYMBOL_WIFI
#define LV_SYMBOL_WIFI           "\xEF\x87\xAB" /*61931, 0xF1EB*/
#endif

#if !defined LV_SYMBOL_WARNING
#define LV_SYMBOL_WARNING           "\xEF\x81\xB1" /*61553, 0xF071*/
#endif

#if !defined LV_SYMBOL_FOLDER
#define LV_SYMBOL_FOLDER           "\xEF\x81\xBB" /*61563, 0xF07B*/
#endif

#if !defined LV_SYMBOL_FILE
#define LV_SYMBOL_FILE           "\xEF\x85\x9B" /*61787, 0xF15B*/
#endif

#if !defined LV_SYMBOL_KEYBOARD
#define LV_SYMBOL_KEYBOARD           "\xEF\x84\x9C" /*61724, 0xF11C*/
#endif

#if !defined LV_SYMBOL_BACKSPACE
#define LV_SYMBOL_BACKSPACE           "\xEF\x95\x9A" /*62810, 0xF55A*/
#endif

#if !defined LV_SYMBOL_SD_CARD
#define LV_SYMBOL_SD_CARD           "\xEF\x9F\x82" /*63426, 0xF7C2*/
#endif

#if !defined LV_SYMBOL_JOG
#define LV_SYMBOL_JOG           "\xEF\x82\xB2" /*61618, 0xF0B2*/
#endif

#if !defined LV_SYMBOL_UP
#define LV_SYMBOL_UP           "\xEF\x81\xB7" /*61559, 0xF077*/
#endif

#if !defined LV_SYMBOL_DOWN
#define LV_SYMBOL_DOWN           "\xEF\x81\xB8" /*61560, 0xF078*/
#endif

#if !defined LV_SYMBOL_LEFT
#define LV_SYMBOL_LEFT           "\xEF\x81\x93" /*61523, 0xF053*/
#endif

#if !defined LV_SYMBOL_RIGHT
#define LV_SYMBOL_RIGHT           "\xEF\x81\x94" /*61524, 0xF054*/
#endif

#if !defined LV_SYMBOL_COMMAND
#define LV_SYMBOL_COMMAND           "\xEF\x84\xA0" /*61728, 0xF120*/
#endif

#if !defined LV_SYMBOL_GAUGE
#define LV_SYMBOL_GAUGE           "\xEF\x98\xA4" /*63012, 0xF624*/
#endif

#if !defined LV_SYMBOL_LANGUAGE
#define LV_SYMBOL_LANGUAGE           "\xEF\x86\xAB" /*61867, 0xF1AB*/
#endif

#if !defined LV_SYMBOL_FAN
#define LV_SYMBOL_FAN           "\xEF\xA1\xA3" /*63587, 0xF863*/
#endif

#if !defined LV_SYMBOL_SPEED
#define LV_SYMBOL_SPEED           "\xEF\x92\x8B" /*62603, 0xF48B*/
#endif

#if !defined LV_SYMBOL_WIZARD
#define LV_SYMBOL_WIZARD           "\xEF\x9C\xAB" /*63275, 0xF72B*/
#endif

#if !defined LV_SYMBOL_LIGHT
#define LV_SYMBOL_LIGHT           "\xEF\x86\x85" /*61829, 0xF185*/
#endif

#if !defined LV_SYMBOL_ENGINE
#define LV_SYMBOL_ENGINE           "\xEF\x97\x81" /*62913, 0xF5C1*/
#endif

#if !defined LV_SYMBOL_LAYERS
#define LV_SYMBOL_LAYERS           "\xEF\x97\xBD" /*62973, 0xF5FD*/
#endif

#if !defined LV_SYMBOL_LEVELING
#define LV_SYMBOL_LEVELING           "\xEE\x92\xB8" /*58552, 0xE4B8*/
#endif

#if !defined LV_SYMBOL_FILAMENT
#define LV_SYMBOL_FILAMENT           "\xEF\x93\x9B" /*62683, 0xF4DB*/
#endif

#if !defined LV_SYMBOL_CENTER
#define LV_SYMBOL_CENTER           "\xEE\x92\xBD" /*58557, 0xE4BD*/
#endif

#if !defined LV_SYMBOL_SEARCH
#define LV_SYMBOL_SEARCH           "\xEF\x80\x82" /*61442, 0xF002*/
#endif

#if !defined LV_SYMBOL_FILAMENT_SENSOR
#define LV_SYMBOL_FILAMENT_SENSOR           "\xEF\x93\x97" /*62679, 0xF4D7*/
#endif

#if !defined LV_SYMBOL_MIST
#define LV_SYMBOL_MIST           "\xEF\x8B\x8C" /*62156, 0xF2CC*/
#endif

#if !defined LV_SYMBOL_UNLOCK
#define LV_SYMBOL_UNLOCK           "\xEF\x84\xBE" /*61758, 0xF13E*/
#endif

#if !defined LV_SYMBOL_LASER_2
#define LV_SYMBOL_LASER_2           "\xEF\x86\x92" /*61842, 0xF192*/
#endif

#if !defined LV_SYMBOL_MILLING
#define LV_SYMBOL_MILLING           "\xEE\x93\x83" /*58563, 0xE4C3*/
#endif

#if !defined LV_SYMBOL_NEW_LINE
#define LV_SYMBOL_NEW_LINE           "\xEF\x8F\xA5" /*62437, 0xF3E5*/
#endif

#if !defined LV_SYMBOL_BLUETOOTH
#define LV_SYMBOL_BLUETOOTH           "\xEF\x8A\x93" /*62099, 0xF293*/
#endif

#if !defined LV_SYMBOL_USB
#define LV_SYMBOL_USB           "\xEF\x8A\x87" /*62087, 0xF287*/
#endif

#if !defined LV_SYMBOL_MORE_INFO
#define LV_SYMBOL_MORE_INFO           "\xEF\x82\xA1" /*61601, 0xF0A1*/
#endif

#if !defined LV_SYMBOL_PLUS
#define LV_SYMBOL_PLUS           "\xEF\x81\x95" /*61525, 0xF055*/
#endif

#if !defined LV_SYMBOL_MINUS
#define LV_SYMBOL_MINUS           "\xEF\x81\x96" /*61526, 0xF056*/
#endif

#if !defined LV_SYMBOL_DUMMY
/** Invalid symbol at (U+F8FF). If written before a string then `lv_img` will show it as a label*/
#define LV_SYMBOL_DUMMY           "\xEF\xA3\xBF"
#endif

enum {
    _LV_STR_SYMBOL_HEAT_BED,
    _LV_STR_SYMBOL_EXTRUDER,
    _LV_STR_SYMBOL_LIST,
    _LV_STR_SYMBOL_SLASH,
    _LV_STR_SYMBOL_STATION_MODE,
    _LV_STR_SYMBOL_ACCESS_POINT,
    _LV_STR_SYMBOL_OK,
    _LV_STR_SYMBOL_PROBE_CHECK,
    _LV_STR_SYMBOL_CLOSE,
    _LV_STR_SYMBOL_POWER,
    _LV_STR_SYMBOL_VOLUME_HIGH,
    _LV_STR_SYMBOL_VOLUME_LOW,
    _LV_STR_SYMBOL_VOLUME_OFF,
    _LV_STR_SYMBOL_SETTINGS,
    _LV_STR_SYMBOL_NO_HEAT_BED,
    _LV_STR_SYMBOL_HEAT_EXTRUDER,
    _LV_STR_SYMBOL_TRASH,
    _LV_STR_SYMBOL_HOME,
    _LV_STR_SYMBOL_DOWNLOAD,
    _LV_STR_SYMBOL_REFRESH,
    _LV_STR_SYMBOL_EDIT,
    _LV_STR_SYMBOL_PREVIOUS,
    _LV_STR_SYMBOL_NEXT,
    _LV_STR_SYMBOL_PLAY,
    _LV_STR_SYMBOL_PAUSE,
    _LV_STR_SYMBOL_SAVE,
    _LV_STR_SYMBOL_MESSAGE,
    _LV_STR_SYMBOL_LASER,
    _LV_STR_SYMBOL_VACCUM,
    _LV_STR_SYMBOL_DISABLE_ALERT,
    _LV_STR_SYMBOL_LOCK,
    _LV_STR_SYMBOL_COOLANT,
    _LV_STR_SYMBOL_STOP,
    _LV_STR_SYMBOL_WIFI,
    _LV_STR_SYMBOL_WARNING,
    _LV_STR_SYMBOL_FOLDER,
    _LV_STR_SYMBOL_FILE,
    _LV_STR_SYMBOL_KEYBOARD,
    _LV_STR_SYMBOL_BACKSPACE,
    _LV_STR_SYMBOL_SD_CARD,
    _LV_STR_SYMBOL_JOG,
    _LV_STR_SYMBOL_UP,
    _LV_STR_SYMBOL_DOWN,
    _LV_STR_SYMBOL_LEFT,
    _LV_STR_SYMBOL_RIGHT,
    _LV_STR_SYMBOL_COMMAND,
    _LV_STR_SYMBOL_GAUGE,
    _LV_STR_SYMBOL_LANGUAGE,
    _LV_STR_SYMBOL_FAN,
    _LV_STR_SYMBOL_SPEED,
    _LV_STR_SYMBOL_WIZARD,
    _LV_STR_SYMBOL_LIGHT,
    _LV_STR_SYMBOL_ENGINE,
    _LV_STR_SYMBOL_LAYERS,
    _LV_STR_SYMBOL_LEVELING,
    _LV_STR_SYMBOL_FILAMENT,
    _LV_STR_SYMBOL_CENTER,
    _LV_STR_SYMBOL_SEARCH,
    _LV_STR_SYMBOL_FILAMENT_SENSOR,
    _LV_STR_SYMBOL_MIST,
    _LV_STR_SYMBOL_UNLOCK,
    _LV_STR_SYMBOL_LASER_2,
    _LV_STR_SYMBOL_MILLING,
    _LV_STR_SYMBOL_NEW_LINE,
    _LV_STR_SYMBOL_BLUETOOTH,
    _LV_STR_SYMBOL_USB,
    _LV_STR_SYMBOL_MORE_INFO,
    _LV_STR_SYMBOL_PLUS,
    _LV_STR_SYMBOL_MINUS,
    _LV_STR_SYMBOL_DUMMY,
};
 
#ifdef __cplusplus
} /*extern "C"*/
#endif
 
#endif /*LV_SYMBOL_DEF_H*/
 
