//This file is generated by a script do not change it
#ifndef LV_SYMBOL_DEF_H
#define LV_SYMBOL_DEF_H
 
#ifdef __cplusplus
extern "C" {
#endif
 
#include "../lv_conf_internal.h" 
 
/*-------------------------------
* Symbols from "normal" font
*-----------------------------*/
#if !defined LV_SYMBOL_BULLET
#define LV_SYMBOL_BULLET          " \xE2\x80\xA2" /*20042, 0x2022*/
#endif

/*-------------------------------
 * Symbols from FontAwesome font
*-----------------------------*/

/*In the font converter use this list as range:
      58728,62153,61642,63231,61458,62745,61452,58774,
      61453,61457,61480,61479,63145,61459,62161,57408,
      62189,58287,61465,61473,62212,61512,61521,61515,
      61516,61639,61664,61671,63343,61942,61475,62172,
      61517,61931,61553,61563,61787,61724,62810,63426,
      61618,61559,61560,61523,61524,61728,63012,61867,
      63587,62603,63275,61829,61531,62973,58552,62683,
      58557,61442,62679,62156,61758,61842,58563,62437,
      62099,62087,61525
*/

/* These symbols can be prefined in the lv_conf.h file.
* If they are not predefined, they will use the following values

*/
